name: Run Tests with Playwright and xvfb

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-traffic-command:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node_index: [1, 2, 3, 4]  # Run 4 parallel jobs with node=1, 2, 3, and 4

    env:
      PROXY_PASSWORD: ${{ secrets.PROXY_PASSWORD }}
      PROXY_PORT: ${{ secrets.PROXY_PORT }}
      PROXY_SERVER: ${{ secrets.PROXY_SERVER }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install xvfb
        run: sudo apt-get update && sudo apt-get install -y xvfb

      - name: Install project dependencies
        run: npm install

      - name: Install Playwright tools
        run: npx playwright install

      - name: Install missing dependencies
        run: npm install generative-bayesian-network

      - name: Run traffic command with xvfb
        run: |
          xvfb-run --auto-servernum --server-num=1 --server-args='-screen 0 1920x1080x24' \
            node traffic.js workflow=1 node=${{ matrix.node_index }}
